# Generated by Django 5.2.8 on 2025-11-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('qualification', models.CharField(max_length=100, verbose_name='Квалификация')),
                ('description', models.TextField(verbose_name='Описание')),
                ('form_of_education', models.CharField(max_length=20, verbose_name='Форма обучения')),
                ('education_level', models.CharField(max_length=20, verbose_name='Уровень образования')),
                ('period_of_study', models.CharField(max_length=20, verbose_name='Срок обучения')),
                ('test', models.TextField(verbose_name='Test')),
            ],
        ),
    ]
