# Generated by Django 5.2.8 on 2025-11-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='test',
        ),
    ]
