# Generated by Django 5.2.8 on 2025-11-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_specialty_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AddField(
            model_name='specialty',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Главная картинка'),
        ),
    ]
