# Generated by Django 5.2.8 on 2025-11-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_specialty_options_specialty_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка в описании'),
        ),
    ]
