# Generated by Django 5.2.8 on 2025-11-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specialty_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('teaching_experience', models.IntegerField(verbose_name='Педагогический стаж')),
                ('qualification_category', models.CharField(max_length=100, verbose_name='Квалификационная категория')),
                ('professional_education', models.TextField(verbose_name='Профессиональное  образование')),
                ('professional_development', models.TextField(verbose_name='Сведения о повышении квалификации')),
                ('awards_and_achievements', models.TextField(verbose_name='Награды и достижения')),
                ('subjects_and_modules_taught', models.TextField(verbose_name='Преподаваемые дисциплины и модули')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
