# Generated by Django 5.2.8 on 2025-11-29 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='lastedit_date',
            field=models.DateTimeField(default=datetime.datetime.now)
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastedit_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
