# Generated by Django 5.2.8 on 2025-11-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_specialty_lastedit_date_teacher_lastedit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='lastedit_date',
            field=models.DateTimeField(),
        ),
    ]
